// export const countries = [
//   {country: 'Afghanistan', code: '93', iso: 'AF'},
//   {country: 'Albania', code: '355', iso: 'AL'},
//   {country: 'Algeria', code: '213', iso: 'DZ'},
//   {country: 'American Samoa', code: '1-684', iso: 'AS'},
//   {country: 'Andorra', code: '376', iso: 'AD'},
//   {country: 'Angola', code: '244', iso: 'AO'},
//   {country: 'Anguilla', code: '1-264', iso: 'AI'},
//   {country: 'Antarctica', code: '672', iso: 'AQ'},
//   {country: 'Antigua and Barbuda', code: '1-268', iso: 'AG'},
//   {country: 'Argentina', code: '54', iso: 'AR'},
//   {country: 'Armenia', code: '374', iso: 'AM'},
//   {country: 'Aruba', code: '297', iso: 'AW'},
//   {country: 'Australia', code: '61', iso: 'AU'},
//   {country: 'Austria', code: '43', iso: 'AT'},
//   {country: 'Azerbaijan', code: '994', iso: 'AZ'},
//   {country: 'Bahamas', code: '1-242', iso: 'BS'},
//   {country: 'Bahrain', code: '973', iso: 'BH'},
//   {country: 'Bangladesh', code: '880', iso: 'BD'},
//   {country: 'Barbados', code: '1-246', iso: 'BB'},
//   {country: 'Belarus', code: '375', iso: 'BY'},
//   {country: 'Belgium', code: '32', iso: 'BE'},
//   {country: 'Belize', code: '501', iso: 'BZ'},
//   {country: 'Benin', code: '229', iso: 'BJ'},
//   {country: 'Bermuda', code: '1-441', iso: 'BM'},
//   {country: 'Bhutan', code: '975', iso: 'BT'},
//   {country: 'Bolivia', code: '591', iso: 'BO'},
//   {country: 'Bosnia and Herzegovina', code: '387', iso: 'BA'},
//   {country: 'Botswana', code: '267', iso: 'BW'},
//   {country: 'Brazil', code: '55', iso: 'BR'},
//   {country: 'British Indian Ocean Territory', code: '246', iso: 'IO'},
//   {country: 'British Virgin Islands', code: '1-284', iso: 'VG'},
//   {country: 'Brunei', code: '673', iso: 'BN'},
//   {country: 'Bulgaria', code: '359', iso: 'BG'},
//   {country: 'Burkina Faso', code: '226', iso: 'BF'},
//   {country: 'Burundi', code: '257', iso: 'BI'},
//   {country: 'Cambodia', code: '855', iso: 'KH'},
//   {country: 'Cameroon', code: '237', iso: 'CM'},
//   {country: 'Canada', code: '1', iso: 'CA'},
//   {country: 'Cape Verde', code: '238', iso: 'CV'},
//   {country: 'Cayman Islands', code: '1-345', iso: 'KY'},
//   {country: 'Central African Republic', code: '236', iso: 'CF'},
//   {country: 'Chad', code: '235', iso: 'TD'},
//   {country: 'Chile', code: '56', iso: 'CL'},
//   {country: 'China', code: '86', iso: 'CN'},
//   {country: 'Christmas Island', code: '61', iso: 'CX'},
//   {country: 'Cocos Islands', code: '61', iso: 'CC'},
//   {country: 'Colombia', code: '57', iso: 'CO'},
//   {country: 'Comoros', code: '269', iso: 'KM'},
//   {country: 'Cook Islands', code: '682', iso: 'CK'},
//   {country: 'Costa Rica', code: '506', iso: 'CR'},
//   {country: 'Croatia', code: '385', iso: 'HR'},
//   {country: 'Cuba', code: '53', iso: 'CU'},
//   {country: 'Curacao', code: '599', iso: 'CW'},
//   {country: 'Cyprus', code: '357', iso: 'CY'},
//   {country: 'Czech Republic', code: '420', iso: 'CZ'},
//   {country: 'Democratic Republic of the Congo', code: '243', iso: 'CD'},
//   {country: 'Denmark', code: '45', iso: 'DK'},
//   {country: 'Djibouti', code: '253', iso: 'DJ'},
//   {country: 'Dominica', code: '1-767', iso: 'DM'},
//   {country: 'Dominican Republic', code: '1-809, 1-829, 1-849', iso: 'DO'},
//   {country: 'East Timor', code: '670', iso: 'TL'},
//   {country: 'Ecuador', code: '593', iso: 'EC'},
//   {country: 'Egypt', code: '20', iso: 'EG'},
//   {country: 'El Salvador', code: '503', iso: 'SV'},
//   {country: 'Equatorial Guinea', code: '240', iso: 'GQ'},
//   {country: 'Eritrea', code: '291', iso: 'ER'},
//   {country: 'Estonia', code: '372', iso: 'EE'},
//   {country: 'Ethiopia', code: '251', iso: 'ET'},
//   {country: 'Falkland Islands', code: '500', iso: 'FK'},
//   {country: 'Faroe Islands', code: '298', iso: 'FO'},
//   {country: 'Fiji', code: '679', iso: 'FJ'},
//   {country: 'Finland', code: '358', iso: 'FI'},
//   {country: 'France', code: '33', iso: 'FR'},
//   {country: 'French Polynesia', code: '689', iso: 'PF'},
//   {country: 'Gabon', code: '241', iso: 'GA'},
//   {country: 'Gambia', code: '220', iso: 'GM'},
//   {country: 'Georgia', code: '995', iso: 'GE'},
//   {country: 'Germany', code: '49', iso: 'DE'},
//   {country: 'Ghana', code: '233', iso: 'GH'},
//   {country: 'Gibraltar', code: '350', iso: 'GI'},
//   {country: 'Greece', code: '30', iso: 'GR'},
//   {country: 'Greenland', code: '299', iso: 'GL'},
//   {country: 'Grenada', code: '1-473', iso: 'GD'},
//   {country: 'Guam', code: '1-671', iso: 'GU'},
//   {country: 'Guatemala', code: '502', iso: 'GT'},
//   {country: 'Guernsey', code: '44-1481', iso: 'GG'},
//   {country: 'Guinea', code: '224', iso: 'GN'},
//   {country: 'Guinea-Bissau', code: '245', iso: 'GW'},
//   {country: 'Guyana', code: '592', iso: 'GY'},
//   {country: 'Haiti', code: '509', iso: 'HT'},
//   {country: 'Honduras', code: '504', iso: 'HN'},
//   {country: 'Hong Kong', code: '852', iso: 'HK'},
//   {country: 'Hungary', code: '36', iso: 'HU'},
//   {country: 'Iceland', code: '354', iso: 'IS'},
//   {country: 'India', code: '91', iso: 'IN'},
//   {country: 'Indonesia', code: '62', iso: 'ID'},
//   {country: 'Iran', code: '98', iso: 'IR'},
//   {country: 'Iraq', code: '964', iso: 'IQ'},
//   {country: 'Ireland', code: '353', iso: 'IE'},
//   {country: 'Isle of Man', code: '44-1624', iso: 'IM'},
//   {country: 'Israel', code: '972', iso: 'IL'},
//   {country: 'Italy', code: '39', iso: 'IT'},
//   {country: 'Ivory Coast', code: '225', iso: 'CI'},
//   {country: 'Jamaica', code: '1-876', iso: 'JM'},
//   {country: 'Japan', code: '81', iso: 'JP'},
//   {country: 'Jersey', code: '44-1534', iso: 'JE'},
//   {country: 'Jordan', code: '962', iso: 'JO'},
//   {country: 'Kazakhstan', code: '7', iso: 'KZ'},
//   {country: 'Kenya', code: '254', iso: 'KE'},
//   {country: 'Kiribati', code: '686', iso: 'KI'},
//   {country: 'Kosovo', code: '383', iso: 'XK'},
//   {country: 'Kuwait', code: '965', iso: 'KW'},
//   {country: 'Kyrgyzstan', code: '996', iso: 'KG'},
//   {country: 'Laos', code: '856', iso: 'LA'},
//   {country: 'Latvia', code: '371', iso: 'LV'},
//   {country: 'Lebanon', code: '961', iso: 'LB'},
//   {country: 'Lesotho', code: '266', iso: 'LS'},
//   {country: 'Liberia', code: '231', iso: 'LR'},
//   {country: 'Libya', code: '218', iso: 'LY'},
//   {country: 'Liechtenstein', code: '423', iso: 'LI'},
//   {country: 'Lithuania', code: '370', iso: 'LT'},
//   {country: 'Luxembourg', code: '352', iso: 'LU'},
//   {country: 'Macao', code: '853', iso: 'MO'},
//   {country: 'Macedonia', code: '389', iso: 'MK'},
//   {country: 'Madagascar', code: '261', iso: 'MG'},
//   {country: 'Malawi', code: '265', iso: 'MW'},
//   {country: 'Malaysia', code: '60', iso: 'MY'},
//   {country: 'Maldives', code: '960', iso: 'MV'},
//   {country: 'Mali', code: '223', iso: 'ML'},
//   {country: 'Malta', code: '356', iso: 'MT'},
//   {country: 'Marshall Islands', code: '692', iso: 'MH'},
//   {country: 'Mauritania', code: '222', iso: 'MR'},
//   {country: 'Mauritius', code: '230', iso: 'MU'},
//   {country: 'Mayotte', code: '262', iso: 'YT'},
//   {country: 'Mexico', code: '52', iso: 'MX'},
//   {country: 'Micronesia', code: '691', iso: 'FM'},
//   {country: 'Moldova', code: '373', iso: 'MD'},
//   {country: 'Monaco', code: '377', iso: 'MC'},
//   {country: 'Mongolia', code: '976', iso: 'MN'},
//   {country: 'Montenegro', code: '382', iso: 'ME'},
//   {country: 'Montserrat', code: '1-664', iso: 'MS'},
//   {country: 'Morocco', code: '212', iso: 'MA'},
//   {country: 'Mozambique', code: '258', iso: 'MZ'},
//   {country: 'Myanmar', code: '95', iso: 'MM'},
//   {country: 'Namibia', code: '264', iso: 'NA'},
//   {country: 'Nauru', code: '674', iso: 'NR'},
//   {country: 'Nepal', code: '977', iso: 'NP'},
//   {country: 'Netherlands', code: '31', iso: 'NL'},
//   {country: 'Netherlands Antilles', code: '599', iso: 'AN'},
//   {country: 'New Caledonia', code: '687', iso: 'NC'},
//   {country: 'New Zealand', code: '64', iso: 'NZ'},
//   {country: 'Nicaragua', code: '505', iso: 'NI'},
//   {country: 'Niger', code: '227', iso: 'NE'},
//   {country: 'Nigeria', code: '234', iso: 'NG'},
//   {country: 'Niue', code: '683', iso: 'NU'},
//   {country: 'North Korea', code: '850', iso: 'KP'},
//   {country: 'Northern Mariana Islands', code: '1-670', iso: 'MP'},
//   {country: 'Norway', code: '47', iso: 'NO'},
//   {country: 'Oman', code: '968', iso: 'OM'},
//   {country: 'Pakistan', code: '92', iso: 'PK'},
//   {country: 'Palau', code: '680', iso: 'PW'},
//   {country: 'Palestine', code: '970', iso: 'PS'},
//   {country: 'Panama', code: '507', iso: 'PA'},
//   {country: 'Papua New Guinea', code: '675', iso: 'PG'},
//   {country: 'Paraguay', code: '595', iso: 'PY'},
//   {country: 'Peru', code: '51', iso: 'PE'},
//   {country: 'Philippines', code: '63', iso: 'PH'},
//   {country: 'Pitcairn', code: '64', iso: 'PN'},
//   {country: 'Poland', code: '48', iso: 'PL'},
//   {country: 'Portugal', code: '351', iso: 'PT'},
//   {country: 'Puerto Rico', code: '1-787, 1-939', iso: 'PR'},
//   {country: 'Qatar', code: '974', iso: 'QA'},
//   {country: 'Republic of the Congo', code: '242', iso: 'CG'},
//   {country: 'Reunion', code: '262', iso: 'RE'},
//   {country: 'Romania', code: '40', iso: 'RO'},
//   {country: 'Russia', code: '7', iso: 'RU'},
//   {country: 'Rwanda', code: '250', iso: 'RW'},
//   {country: 'Saint Barthelemy', code: '590', iso: 'BL'},
//   {country: 'Saint Helena', code: '290', iso: 'SH'},
//   {country: 'Saint Kitts and Nevis', code: '1-869', iso: 'KN'},
//   {country: 'Saint Lucia', code: '1-758', iso: 'LC'},
//   {country: 'Saint Martin', code: '590', iso: 'MF'},
//   {country: 'Saint Pierre and Miquelon', code: '508', iso: 'PM'},
//   {country: 'Saint Vincent and the Grenadines', code: '1-784', iso: 'VC'},
//   {country: 'Samoa', code: '685', iso: 'WS'},
//   {country: 'San Marino', code: '378', iso: 'SM'},
//   {country: 'Sao Tome and Principe', code: '239', iso: 'ST'},
//   {country: 'Saudi Arabia', code: '966', iso: 'SA'},
//   {country: 'Senegal', code: '221', iso: 'SN'},
//   {country: 'Serbia', code: '381', iso: 'RS'},
//   {country: 'Seychelles', code: '248', iso: 'SC'},
//   {country: 'Sierra Leone', code: '232', iso: 'SL'},
//   {country: 'Singapore', code: '65', iso: 'SG'},
//   {country: 'Sint Maarten', code: '1-721', iso: 'SX'},
//   {country: 'Slovakia', code: '421', iso: 'SK'},
//   {country: 'Slovenia', code: '386', iso: 'SI'},
//   {country: 'Solomon Islands', code: '677', iso: 'SB'},
//   {country: 'Somalia', code: '252', iso: 'SO'},
//   {country: 'South Africa', code: '27', iso: 'ZA'},
//   {country: 'South Korea', code: '82', iso: 'KR'},
//   {country: 'South Sudan', code: '211', iso: 'SS'},
//   {country: 'Spain', code: '34', iso: 'ES'},
//   {country: 'Sri Lanka', code: '94', iso: 'LK'},
//   {country: 'Sudan', code: '249', iso: 'SD'},
//   {country: 'Suriname', code: '597', iso: 'SR'},
//   {country: 'Svalbard and Jan Mayen', code: '47', iso: 'SJ'},
//   {country: 'Swaziland', code: '268', iso: 'SZ'},
//   {country: 'Sweden', code: '46', iso: 'SE'},
//   {country: 'Switzerland', code: '41', iso: 'CH'},
//   {country: 'Syria', code: '963', iso: 'SY'},
//   {country: 'Taiwan', code: '886', iso: 'TW'},
//   {country: 'Tajikistan', code: '992', iso: 'TJ'},
//   {country: 'Tanzania', code: '255', iso: 'TZ'},
//   {country: 'Thailand', code: '66', iso: 'TH'},
//   {country: 'Togo', code: '228', iso: 'TG'},
//   {country: 'Tokelau', code: '690', iso: 'TK'},
//   {country: 'Tonga', code: '676', iso: 'TO'},
//   {country: 'Trinidad and Tobago', code: '1-868', iso: 'TT'},
//   {country: 'Tunisia', code: '216', iso: 'TN'},
//   {country: 'Turkey', code: '90', iso: 'TR'},
//   {country: 'Turkmenistan', code: '993', iso: 'TM'},
//   {country: 'Turks and Caicos Islands', code: '1-649', iso: 'TC'},
//   {country: 'Tuvalu', code: '688', iso: 'TV'},
//   {country: 'U.S. Virgin Islands', code: '1-340', iso: 'VI'},
//   {country: 'Uganda', code: '256', iso: 'UG'},
//   {country: 'Ukraine', code: '380', iso: 'UA'},
//   {country: 'United Arab Emirates', code: '971', iso: 'AE'},
//   {country: 'United Kingdom', code: '44', iso: 'GB'},
//   {country: 'United States', code: '1', iso: 'US'},
//   {country: 'Uruguay', code: '598', iso: 'UY'},
//   {country: 'Uzbekistan', code: '998', iso: 'UZ'},
//   {country: 'Vanuatu', code: '678', iso: 'VU'},
//   {country: 'Vatican', code: '379', iso: 'VA'},
//   {country: 'Venezuela', code: '58', iso: 'VE'},
//   {country: 'Vietnam', code: '84', iso: 'VN'},
//   {country: 'Wallis and Futuna', code: '681', iso: 'WF'},
//   {country: 'Western Sahara', code: '212', iso: 'EH'},
//   {country: 'Yemen', code: '967', iso: 'YE'},
//   {country: 'Zambia', code: '260', iso: 'ZM'},
//   {country: 'Zimbabwe', code: '263', iso: 'ZW'},
// ];

export const countries = [
  {
    country: 'Afghanistan',
    code: '93',
    iso: 'AF',
    currency_code: 'AFN',
  },
  {
    country: 'Albania',
    code: '355',
    iso: 'AL',
    currency_code: 'ALL',
  },
  {
    country: 'Algeria',
    code: '213',
    iso: 'DZ',
    currency_code: 'DZD',
  },
  {
    country: 'American Samoa',
    code: '1-684',
    iso: 'AS',
    currency_code: 'USD',
  },
  {
    country: 'Andorra',
    code: '376',
    iso: 'AD',
    currency_code: 'EUR',
  },
  {
    country: 'Angola',
    code: '244',
    iso: 'AO',
    currency_code: 'AOA',
  },
  {
    country: 'Anguilla',
    code: '1-264',
    iso: 'AI',
    currency_code: 'XCD',
  },
  {
    country: 'Antarctica',
    code: '672',
    iso: 'AQ',
    currency_code: 'None',
  },
  {
    country: 'Antigua and Barbuda',
    code: '1-268',
    iso: 'AG',
    currency_code: 'XCD',
  },
  {
    country: 'Argentina',
    code: '54',
    iso: 'AR',
    currency_code: 'ARS',
  },
  {
    country: 'Armenia',
    code: '374',
    iso: 'AM',
    currency_code: 'AMD',
  },
  {
    country: 'Aruba',
    code: '297',
    iso: 'AW',
    currency_code: 'AWG',
  },
  {
    country: 'Australia',
    code: '61',
    iso: 'AU',
    currency_code: 'AUD',
  },
  {
    country: 'Austria',
    code: '43',
    iso: 'AT',
    currency_code: 'EUR',
  },
  {
    country: 'Azerbaijan',
    code: '994',
    iso: 'AZ',
    currency_code: 'AZN',
  },
  {
    country: 'Bahamas',
    code: '1-242',
    iso: 'BS',
    currency_code: 'BSD',
  },
  {
    country: 'Bahrain',
    code: '973',
    iso: 'BH',
    currency_code: 'BHD',
  },
  {
    country: 'Bangladesh',
    code: '880',
    iso: 'BD',
    currency_code: 'BDT',
  },
  {
    country: 'Barbados',
    code: '1-246',
    iso: 'BB',
    currency_code: 'BBD',
  },
  {
    country: 'Belarus',
    code: '375',
    iso: 'BY',
    currency_code: 'BYN',
  },
  {
    country: 'Belgium',
    code: '32',
    iso: 'BE',
    currency_code: 'EUR',
  },
  {
    country: 'Belize',
    code: '501',
    iso: 'BZ',
    currency_code: 'BZD',
  },
  {
    country: 'Benin',
    code: '229',
    iso: 'BJ',
    currency_code: 'XOF',
  },
  {
    country: 'Bermuda',
    code: '1-441',
    iso: 'BM',
    currency_code: 'BMD',
  },
  {
    country: 'Bhutan',
    code: '975',
    iso: 'BT',
    currency_code: 'BTN',
  },
  {
    country: 'Bolivia',
    code: '591',
    iso: 'BO',
    currency_code: 'BOB',
  },
  {
    country: 'Bosnia and Herzegovina',
    code: '387',
    iso: 'BA',
    currency_code: 'BAM',
  },
  {
    country: 'Botswana',
    code: '267',
    iso: 'BW',
    currency_code: 'BWP',
  },
  {
    country: 'Brazil',
    code: '55',
    iso: 'BR',
    currency_code: 'BRL',
  },
  {
    country: 'British Indian Ocean Territory',
    code: '246',
    iso: 'IO',
    currency_code: 'USD',
  },
  {
    country: 'British Virgin Islands',
    code: '1-284',
    iso: 'VG',
    currency_code: 'USD',
  },
  {
    country: 'Brunei',
    code: '673',
    iso: 'BN',
    currency_code: 'BND',
  },
  {
    country: 'Bulgaria',
    code: '359',
    iso: 'BG',
    currency_code: 'BGN',
  },
  {
    country: 'Burkina Faso',
    code: '226',
    iso: 'BF',
    currency_code: 'XOF',
  },
  {
    country: 'Burundi',
    code: '257',
    iso: 'BI',
    currency_code: 'BIF',
  },
  {
    country: 'Cambodia',
    code: '855',
    iso: 'KH',
    currency_code: 'KHR',
  },
  {
    country: 'Cameroon',
    code: '237',
    iso: 'CM',
    currency_code: 'XAF',
  },
  {
    country: 'Canada',
    code: '1',
    iso: 'CA',
    currency_code: 'CAD',
  },
  {
    country: 'Cape Verde',
    code: '238',
    iso: 'CV',
    currency_code: 'CVE',
  },
  {
    country: 'Cayman Islands',
    code: '1-345',
    iso: 'KY',
    currency_code: 'KYD',
  },
  {
    country: 'Central African Republic',
    code: '236',
    iso: 'CF',
    currency_code: 'XAF',
  },
  {
    country: 'Chad',
    code: '235',
    iso: 'TD',
    currency_code: 'XAF',
  },
  {
    country: 'Chile',
    code: '56',
    iso: 'CL',
    currency_code: 'CLP',
  },

  {country: 'China', code: '86', iso: 'CN', currency_code: 'CNY'},
  {country: 'Christmas Island', code: '61', iso: 'CX', currency_code: 'AUD'},
  {country: 'Cocos Islands', code: '61', iso: 'CC', currency_code: 'AUD'},
  {country: 'Colombia', code: '57', iso: 'CO', currency_code: 'COP'},
  {country: 'Comoros', code: '269', iso: 'KM', currency_code: 'KMF'},
  {country: 'Cook Islands', code: '682', iso: 'CK', currency_code: 'NZD'},
  {country: 'Costa Rica', code: '506', iso: 'CR', currency_code: 'CRC'},
  {country: 'Croatia', code: '385', iso: 'HR', currency_code: 'HRK'},
  {country: 'Cuba', code: '53', iso: 'CU', currency_code: 'CUP'},
  {country: 'Curacao', code: '599', iso: 'CW', currency_code: 'ANG'},
  {country: 'Cyprus', code: '357', iso: 'CY', currency_code: 'EUR'},
  {country: 'Czech Republic', code: '420', iso: 'CZ', currency_code: 'CZK'},
  {
    country: 'Democratic Republic of the Congo',
    code: '243',
    iso: 'CD',
    currency_code: 'CDF',
  },
  {country: 'Denmark', code: '45', iso: 'DK', currency_code: 'DKK'},
  {country: 'Djibouti', code: '253', iso: 'DJ', currency_code: 'DJF'},
  {country: 'Dominica', code: '1-767', iso: 'DM', currency_code: 'XCD'},
  {
    country: 'Dominican Republic',
    code: '1-809, 1-829, 1-849',
    iso: 'DO',
    currency_code: 'DOP',
  },
  {country: 'East Timor', code: '670', iso: 'TL', currency_code: 'USD'},
  {country: 'Ecuador', code: '593', iso: 'EC', currency_code: 'USD'},
  {country: 'Egypt', code: '20', iso: 'EG', currency_code: 'EGP'},
  {country: 'El Salvador', code: '503', iso: 'SV', currency_code: 'USD'},
  {country: 'Equatorial Guinea', code: '240', iso: 'GQ', currency_code: 'XAF'},
  {country: 'Eritrea', code: '291', iso: 'ER', currency_code: 'ERN'},
  {country: 'Estonia', code: '372', iso: 'EE', currency_code: 'EUR'},
  {country: 'Ethiopia', code: '251', iso: 'ET', currency_code: 'ETB'},
  {country: 'Falkland Islands', code: '500', iso: 'FK', currency_code: 'FKP'},
  {country: 'Faroe Islands', code: '298', iso: 'FO', currency_code: 'DKK'},
  {country: 'Fiji', code: '679', iso: 'FJ', currency_code: 'FJD'},
  {country: 'Finland', code: '358', iso: 'FI', currency_code: 'EUR'},
  {country: 'France', code: '33', iso: 'FR', currency_code: 'EUR'},
  {country: 'French Polynesia', code: '689', iso: 'PF', currency_code: 'XPF'},
  {country: 'Gabon', code: '241', iso: 'GA', currency_code: 'XAF'},
  {country: 'Gambia', code: '220', iso: 'GM', currency_code: 'GMD'},
  {country: 'Georgia', code: '995', iso: 'GE', currency_code: 'GEL'},
  {country: 'Germany', code: '49', iso: 'DE', currency_code: 'EUR'},
  {country: 'Ghana', code: '233', iso: 'GH', currency_code: 'GHS'},
  {country: 'Gibraltar', code: '350', iso: 'GI', currency_code: 'GIP'},
  {country: 'Greece', code: '30', iso: 'GR', currency_code: 'EUR'},
  {country: 'Greenland', code: '299', iso: 'GL', currency_code: 'DKK'},
  {country: 'Grenada', code: '1-473', iso: 'GD', currency_code: 'XCD'},
  {country: 'Guam', code: '1-671', iso: 'GU', currency_code: 'USD'},
  {country: 'Guatemala', code: '502', iso: 'GT', currency_code: 'GTQ'},
  {country: 'Guernsey', code: '44-1481', iso: 'GG', currency_code: 'GBP'},
  {country: 'Guinea', code: '224', iso: 'GN', currency_code: 'GNF'},
  {country: 'Guinea-Bissau', code: '245', iso: 'GW', currency_code: 'XOF'},
  {country: 'Guyana', code: '592', iso: 'GY', currency_code: 'GYD'},
  {country: 'Haiti', code: '509', iso: 'HT', currency_code: 'HTG'},
  {country: 'Honduras', code: '504', iso: 'HN', currency_code: 'HNL'},
  {country: 'Hong Kong', code: '852', iso: 'HK', currency_code: 'HKD'},
  {country: 'Hungary', code: '36', iso: 'HU', currency_code: 'HUF'},
  {country: 'Iceland', code: '354', iso: 'IS', currency_code: 'ISK'},
  {country: 'India', code: '91', iso: 'IN', currency_code: 'INR'},
  {country: 'Indonesia', code: '62', iso: 'ID', currency_code: 'IDR'},
  {country: 'Iran', code: '98', iso: 'IR', currency_code: 'IRR'},
  {country: 'Iraq', code: '964', iso: 'IQ', currency_code: 'IQD'},
  {country: 'Ireland', code: '353', iso: 'IE', currency_code: 'EUR'},
  {country: 'Isle of Man', code: '44-1624', iso: 'IM', currency_code: 'GBP'},
  {country: 'Israel', code: '972', iso: 'IL', currency_code: 'ILS'},
  {country: 'Italy', code: '39', iso: 'IT', currency_code: 'EUR'},
  {country: 'Ivory Coast', code: '225', iso: 'CI', currency_code: 'XOF'},
  {country: 'Jamaica', code: '1-876', iso: 'JM', currency_code: 'JMD'},
  {country: 'Japan', code: '81', iso: 'JP', currency_code: 'JPY'},
  {country: 'Jersey', code: '44-1534', iso: 'JE', currency_code: 'GBP'},
  {country: 'Jordan', code: '962', iso: 'JO', currency_code: 'JOD'},
  {country: 'Kazakhstan', code: '7', iso: 'KZ', currency_code: 'KZT'},
  {country: 'Kenya', code: '254', iso: 'KE', currency_code: 'KES'},
  {country: 'Kiribati', code: '686', iso: 'KI', currency_code: 'AUD'},
  {country: 'Kosovo', code: '383', iso: 'XK', currency_code: 'EUR'},
  {country: 'Kuwait', code: '965', iso: 'KW', currency_code: 'KWD'},
  {country: 'Kyrgyzstan', code: '996', iso: 'KG', currency_code: 'KGS'},
  {country: 'Laos', code: '856', iso: 'LA', currency_code: 'LAK'},
  {country: 'Latvia', code: '371', iso: 'LV', currency_code: 'EUR'},
  {country: 'Lebanon', code: '961', iso: 'LB', currency_code: 'LBP'},
  {country: 'Lesotho', code: '266', iso: 'LS', currency_code: 'LSL'},
  {country: 'Liberia', code: '231', iso: 'LR', currency_code: 'LRD'},
  {country: 'Libya', code: '218', iso: 'LY', currency_code: 'LYD'},
  {country: 'Liechtenstein', code: '423', iso: 'LI', currency_code: 'CHF'},
  {country: 'Lithuania', code: '370', iso: 'LT', currency_code: 'EUR'},
  {country: 'Luxembourg', code: '352', iso: 'LU', currency_code: 'EUR'},
  {country: 'Macao', code: '853', iso: 'MO', currency_code: 'MOP'},
  {country: 'Macedonia', code: '389', iso: 'MK', currency_code: 'MKD'},
  {country: 'Madagascar', code: '261', iso: 'MG', currency_code: 'MGA'},
  {country: 'Malawi', code: '265', iso: 'MW', currency_code: 'MWK'},
  {country: 'Malaysia', code: '60', iso: 'MY', currency_code: 'MYR'},
  {country: 'Maldives', code: '960', iso: 'MV', currency_code: 'MVR'},
  {country: 'Mali', code: '223', iso: 'ML', currency_code: 'XOF'},
  {country: 'Malta', code: '356', iso: 'MT', currency_code: 'EUR'},
  {country: 'Marshall Islands', code: '692', iso: 'MH', currency_code: 'USD'},
  {country: 'Mauritania', code: '222', iso: 'MR', currency_code: 'MRU'},
  {country: 'Mauritius', code: '230', iso: 'MU', currency_code: 'MUR'},
  {country: 'Mayotte', code: '262', iso: 'YT', currency_code: 'EUR'},
  {country: 'Mexico', code: '52', iso: 'MX', currency_code: 'MXN'},
  {country: 'Micronesia', code: '691', iso: 'FM', currency_code: 'USD'},
  {country: 'Moldova', code: '373', iso: 'MD', currency_code: 'MDL'},
  {country: 'Monaco', code: '377', iso: 'MC', currency_code: 'EUR'},
  {country: 'Mongolia', code: '976', iso: 'MN', currency_code: 'MNT'},
  {country: 'Montenegro', code: '382', iso: 'ME', currency_code: 'EUR'},
  {country: 'Montserrat', code: '1-664', iso: 'MS', currency_code: 'XCD'},
  {country: 'Morocco', code: '212', iso: 'MA', currency_code: 'MAD'},
  {country: 'Mozambique', code: '258', iso: 'MZ', currency_code: 'MZN'},
  {country: 'Myanmar', code: '95', iso: 'MM', currency_code: 'MMK'},
  {country: 'Namibia', code: '264', iso: 'NA', currency_code: 'NAD'},
  {country: 'Nauru', code: '674', iso: 'NR', currency_code: 'AUD'},
  {country: 'Nepal', code: '977', iso: 'NP', currency_code: 'NPR'},
  {country: 'Netherlands', code: '31', iso: 'NL', currency_code: 'EUR'},
  {
    country: 'Netherlands Antilles',
    code: '599',
    iso: 'AN',
    currency_code: 'ANG',
  },
  {country: 'New Caledonia', code: '687', iso: 'NC', currency_code: 'XPF'},
  {country: 'New Zealand', code: '64', iso: 'NZ', currency_code: 'NZD'},
  {country: 'Nicaragua', code: '505', iso: 'NI', currency_code: 'NIO'},
  {country: 'Niger', code: '227', iso: 'NE', currency_code: 'XOF'},
  {country: 'Nigeria', code: '234', iso: 'NG', currency_code: 'NGN'},
  {country: 'Niue', code: '683', iso: 'NU', currency_code: 'NZD'},
  {country: 'North Korea', code: '850', iso: 'KP', currency_code: 'KPW'},
  {
    country: 'Northern Mariana Islands',
    code: '1-670',
    iso: 'MP',
    currency_code: 'USD',
  },
  {country: 'Norway', code: '47', iso: 'NO', currency_code: 'NOK'},

  {country: 'Norway', code: '47', iso: 'NO', currency_code: 'NOK'},
  {country: 'Oman', code: '968', iso: 'OM', currency_code: 'OMR'},
  {country: 'Pakistan', code: '92', iso: 'PK', currency_code: 'PKR'},
  {country: 'Palau', code: '680', iso: 'PW', currency_code: 'USD'},
  {country: 'Palestine', code: '970', iso: 'PS', currency_code: 'ILS'},
  {country: 'Panama', code: '507', iso: 'PA', currency_code: 'PAB'},
  {country: 'Papua New Guinea', code: '675', iso: 'PG', currency_code: 'PGK'},
  {country: 'Paraguay', code: '595', iso: 'PY', currency_code: 'PYG'},
  {country: 'Peru', code: '51', iso: 'PE', currency_code: 'PEN'},
  {country: 'Philippines', code: '63', iso: 'PH', currency_code: 'PHP'},
  {country: 'Pitcairn', code: '64', iso: 'PN', currency_code: 'NZD'},
  {country: 'Poland', code: '48', iso: 'PL', currency_code: 'PLN'},
  {country: 'Portugal', code: '351', iso: 'PT', currency_code: 'EUR'},
  {
    country: 'Puerto Rico',
    code: '1-787, 1-939',
    iso: 'PR',
    currency_code: 'USD',
  },
  {country: 'Qatar', code: '974', iso: 'QA', currency_code: 'QAR'},
  {
    country: 'Republic of the Congo',
    code: '242',
    iso: 'CG',
    currency_code: 'XAF',
  },
  {country: 'Reunion', code: '262', iso: 'RE', currency_code: 'EUR'},
  {country: 'Romania', code: '40', iso: 'RO', currency_code: 'RON'},
  {country: 'Russia', code: '7', iso: 'RU', currency_code: 'RUB'},
  {country: 'Rwanda', code: '250', iso: 'RW', currency_code: 'RWF'},
  {country: 'Saint Barthelemy', code: '590', iso: 'BL', currency_code: 'EUR'},
  {country: 'Saint Helena', code: '290', iso: 'SH', currency_code: 'SHP'},
  {
    country: 'Saint Kitts and Nevis',
    code: '1-869',
    iso: 'KN',
    currency_code: 'XCD',
  },
  {country: 'Saint Lucia', code: '1-758', iso: 'LC', currency_code: 'XCD'},
  {country: 'Saint Martin', code: '590', iso: 'MF', currency_code: 'EUR'},
  {
    country: 'Saint Pierre and Miquelon',
    code: '508',
    iso: 'PM',
    currency_code: 'EUR',
  },
  {
    country: 'Saint Vincent and the Grenadines',
    code: '1-784',
    iso: 'VC',
    currency_code: 'XCD',
  },
  {country: 'Samoa', code: '685', iso: 'WS', currency_code: 'WST'},
  {country: 'San Marino', code: '378', iso: 'SM', currency_code: 'EUR'},
  {
    country: 'Sao Tome and Principe',
    code: '239',
    iso: 'ST',
    currency_code: 'STN',
  },
  {country: 'Saudi Arabia', code: '966', iso: 'SA', currency_code: 'SAR'},
  {country: 'Senegal', code: '221', iso: 'SN', currency_code: 'XOF'},
  {country: 'Serbia', code: '381', iso: 'RS', currency_code: 'RSD'},
  {country: 'Seychelles', code: '248', iso: 'SC', currency_code: 'SCR'},
  {country: 'Sierra Leone', code: '232', iso: 'SL', currency_code: 'SLL'},
  {country: 'Singapore', code: '65', iso: 'SG', currency_code: 'SGD'},
  {country: 'Sint Maarten', code: '1-721', iso: 'SX', currency_code: 'ANG'},
  {country: 'Slovakia', code: '421', iso: 'SK', currency_code: 'EUR'},
  {country: 'Slovenia', code: '386', iso: 'SI', currency_code: 'EUR'},
  {country: 'Solomon Islands', code: '677', iso: 'SB', currency_code: 'SBD'},
  {country: 'Somalia', code: '252', iso: 'SO', currency_code: 'SOS'},
  {country: 'South Africa', code: '27', iso: 'ZA', currency_code: 'ZAR'},
  {country: 'South Korea', code: '82', iso: 'KR', currency_code: 'KRW'},
  {country: 'South Sudan', code: '211', iso: 'SS', currency_code: 'SSP'},
  {country: 'Spain', code: '34', iso: 'ES', currency_code: 'EUR'},
  {country: 'Sri Lanka', code: '94', iso: 'LK', currency_code: 'LKR'},
  {country: 'Sudan', code: '249', iso: 'SD', currency_code: 'SDG'},
  {country: 'Suriname', code: '597', iso: 'SR', currency_code: 'SRD'},
  {
    country: 'Svalbard and Jan Mayen',
    code: '47',
    iso: 'SJ',
    currency_code: 'NOK',
  },
  {country: 'Swaziland', code: '268', iso: 'SZ', currency_code: 'SZL'},
  {country: 'Sweden', code: '46', iso: 'SE', currency_code: 'SEK'},
  {country: 'Switzerland', code: '41', iso: 'CH', currency_code: 'CHF'},
  {country: 'Syria', code: '963', iso: 'SY', currency_code: 'SYP'},
  {country: 'Taiwan', code: '886', iso: 'TW', currency_code: 'TWD'},
  {country: 'Tajikistan', code: '992', iso: 'TJ', currency_code: 'TJS'},
  {country: 'Tanzania', code: '255', iso: 'TZ', currency_code: 'TZS'},
  {country: 'Thailand', code: '66', iso: 'TH', currency_code: 'THB'},
  {country: 'Togo', code: '228', iso: 'TG', currency_code: 'XOF'},
  {country: 'Tokelau', code: '690', iso: 'TK', currency_code: 'NZD'},
  {country: 'Tonga', code: '676', iso: 'TO', currency_code: 'TOP'},
  {
    country: 'Trinidad and Tobago',
    code: '1-868',
    iso: 'TT',
    currency_code: 'TTD',
  },
  {country: 'Tunisia', code: '216', iso: 'TN', currency_code: 'TND'},
  {country: 'Turkey', code: '90', iso: 'TR', currency_code: 'TRY'},
  {country: 'Turkmenistan', code: '993', iso: 'TM', currency_code: 'TMT'},
  {
    country: 'Turks and Caicos Islands',
    code: '1-649',
    iso: 'TC',
    currency_code: 'USD',
  },
  {country: 'Tuvalu', code: '688', iso: 'TV', currency_code: 'AUD'},
  {
    country: 'U.S. Virgin Islands',
    code: '1-340',
    iso: 'VI',
    currency_code: 'USD',
  },
  {country: 'Uganda', code: '256', iso: 'UG', currency_code: 'UGX'},
  {country: 'Ukraine', code: '380', iso: 'UA', currency_code: 'UAH'},
  {
    country: 'United Arab Emirates',
    code: '971',
    iso: 'AE',
    currency_code: 'AED',
  },
  {country: 'United Kingdom', code: '44', iso: 'GB', currency_code: 'GBP'},
  {country: 'United States', code: '1', iso: 'US', currency_code: 'USD'},
  {country: 'Uruguay', code: '598', iso: 'UY', currency_code: 'UYU'},
  {country: 'Uzbekistan', code: '998', iso: 'UZ', currency_code: 'UZS'},
  {country: 'Vanuatu', code: '678', iso: 'VU', currency_code: 'VUV'},
  {country: 'Vatican', code: '379', iso: 'VA', currency_code: 'EUR'},
  {country: 'Venezuela', code: '58', iso: 'VE', currency_code: 'VES'},
  {country: 'Vietnam', code: '84', iso: 'VN', currency_code: 'VND'},
  {country: 'Wallis and Futuna', code: '681', iso: 'WF', currency_code: 'XPF'},
  {country: 'Western Sahara', code: '212', iso: 'EH', currency_code: 'MAD'},
  {country: 'Yemen', code: '967', iso: 'YE', currency_code: 'YER'},
  {country: 'Zambia', code: '260', iso: 'ZM', currency_code: 'ZMW'},
  {country: 'Zimbabwe', code: '263', iso: 'ZW', currency_code: 'ZWL'},
];

// export const currencyCountryCode = {
//   USD: {
//     symbol: '$',
//     name: 'US Dollar',
//     symbol_native: '$',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'USD',
//     name_plural: 'US dollars',
//   },
//   CAD: {
//     symbol: 'CA$',
//     name: 'Canadian Dollar',
//     symbol_native: '$',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'CAD',
//     name_plural: 'Canadian dollars',
//   },
//   EUR: {
//     symbol: '€',
//     name: 'Euro',
//     symbol_native: '€',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'EUR',
//     name_plural: 'euros',
//   },
//   AED: {
//     symbol: 'AED',
//     name: 'United Arab Emirates Dirham',
//     symbol_native: 'د.إ.‏',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'AED',
//     name_plural: 'UAE dirhams',
//   },
//   AFN: {
//     symbol: 'Af',
//     name: 'Afghan Afghani',
//     symbol_native: '؋',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'AFN',
//     name_plural: 'Afghan Afghanis',
//   },
//   ALL: {
//     symbol: 'ALL',
//     name: 'Albanian Lek',
//     symbol_native: 'Lek',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'ALL',
//     name_plural: 'Albanian lekë',
//   },
//   AMD: {
//     symbol: 'AMD',
//     name: 'Armenian Dram',
//     symbol_native: 'դր.',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'AMD',
//     name_plural: 'Armenian drams',
//   },
//   ARS: {
//     symbol: 'AR$',
//     name: 'Argentine Peso',
//     symbol_native: '$',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'ARS',
//     name_plural: 'Argentine pesos',
//   },
//   AUD: {
//     symbol: 'AU$',
//     name: 'Australian Dollar',
//     symbol_native: '$',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'AUD',
//     name_plural: 'Australian dollars',
//   },
//   AZN: {
//     symbol: 'man.',
//     name: 'Azerbaijani Manat',
//     symbol_native: 'ман.',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'AZN',
//     name_plural: 'Azerbaijani manats',
//   },
//   BAM: {
//     symbol: 'KM',
//     name: 'Bosnia-Herzegovina Convertible Mark',
//     symbol_native: 'KM',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'BAM',
//     name_plural: 'Bosnia-Herzegovina convertible marks',
//   },
//   BDT: {
//     symbol: 'Tk',
//     name: 'Bangladeshi Taka',
//     symbol_native: '৳',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'BDT',
//     name_plural: 'Bangladeshi takas',
//   },
//   BGN: {
//     symbol: 'BGN',
//     name: 'Bulgarian Lev',
//     symbol_native: 'лв.',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'BGN',
//     name_plural: 'Bulgarian leva',
//   },
//   BHD: {
//     symbol: 'BD',
//     name: 'Bahraini Dinar',
//     symbol_native: 'د.ب.‏',
//     decimal_digits: 3,
//     rounding: 0,
//     code: 'BHD',
//     name_plural: 'Bahraini dinars',
//   },
//   BIF: {
//     symbol: 'FBu',
//     name: 'Burundian Franc',
//     symbol_native: 'FBu',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'BIF',
//     name_plural: 'Burundian francs',
//   },
//   BND: {
//     symbol: 'BN$',
//     name: 'Brunei Dollar',
//     symbol_native: '$',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'BND',
//     name_plural: 'Brunei dollars',
//   },
//   BOB: {
//     symbol: 'Bs',
//     name: 'Bolivian Boliviano',
//     symbol_native: 'Bs',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'BOB',
//     name_plural: 'Bolivian bolivianos',
//   },
//   BRL: {
//     symbol: 'R$',
//     name: 'Brazilian Real',
//     symbol_native: 'R$',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'BRL',
//     name_plural: 'Brazilian reals',
//   },
//   BWP: {
//     symbol: 'BWP',
//     name: 'Botswanan Pula',
//     symbol_native: 'P',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'BWP',
//     name_plural: 'Botswanan pulas',
//   },
//   BYN: {
//     symbol: 'Br',
//     name: 'Belarusian Ruble',
//     symbol_native: 'руб.',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'BYN',
//     name_plural: 'Belarusian rubles',
//   },
//   BZD: {
//     symbol: 'BZ$',
//     name: 'Belize Dollar',
//     symbol_native: '$',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'BZD',
//     name_plural: 'Belize dollars',
//   },
//   CDF: {
//     symbol: 'CDF',
//     name: 'Congolese Franc',
//     symbol_native: 'FrCD',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'CDF',
//     name_plural: 'Congolese francs',
//   },
//   CHF: {
//     symbol: 'CHF',
//     name: 'Swiss Franc',
//     symbol_native: 'CHF',
//     decimal_digits: 2,
//     rounding: 0.05,
//     code: 'CHF',
//     name_plural: 'Swiss francs',
//   },
//   CLP: {
//     symbol: 'CL$',
//     name: 'Chilean Peso',
//     symbol_native: '$',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'CLP',
//     name_plural: 'Chilean pesos',
//   },
//   CNY: {
//     symbol: 'CN¥',
//     name: 'Chinese Yuan',
//     symbol_native: 'CN¥',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'CNY',
//     name_plural: 'Chinese yuan',
//   },
//   COP: {
//     symbol: 'CO$',
//     name: 'Colombian Peso',
//     symbol_native: '$',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'COP',
//     name_plural: 'Colombian pesos',
//   },
//   CRC: {
//     symbol: '₡',
//     name: 'Costa Rican Colón',
//     symbol_native: '₡',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'CRC',
//     name_plural: 'Costa Rican colóns',
//   },
//   CVE: {
//     symbol: 'CV$',
//     name: 'Cape Verdean Escudo',
//     symbol_native: 'CV$',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'CVE',
//     name_plural: 'Cape Verdean escudos',
//   },
//   CZK: {
//     symbol: 'Kč',
//     name: 'Czech Republic Koruna',
//     symbol_native: 'Kč',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'CZK',
//     name_plural: 'Czech Republic korunas',
//   },
//   DJF: {
//     symbol: 'Fdj',
//     name: 'Djiboutian Franc',
//     symbol_native: 'Fdj',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'DJF',
//     name_plural: 'Djiboutian francs',
//   },
//   DKK: {
//     symbol: 'Dkr',
//     name: 'Danish Krone',
//     symbol_native: 'kr',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'DKK',
//     name_plural: 'Danish kroner',
//   },
//   DOP: {
//     symbol: 'RD$',
//     name: 'Dominican Peso',
//     symbol_native: 'RD$',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'DOP',
//     name_plural: 'Dominican pesos',
//   },
//   DZD: {
//     symbol: 'DA',
//     name: 'Algerian Dinar',
//     symbol_native: 'د.ج.‏',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'DZD',
//     name_plural: 'Algerian dinars',
//   },
//   EEK: {
//     symbol: 'Ekr',
//     name: 'Estonian Kroon',
//     symbol_native: 'kr',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'EEK',
//     name_plural: 'Estonian kroons',
//   },
//   EGP: {
//     symbol: 'EGP',
//     name: 'Egyptian Pound',
//     symbol_native: 'ج.م.‏',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'EGP',
//     name_plural: 'Egyptian pounds',
//   },
//   ERN: {
//     symbol: 'Nfk',
//     name: 'Eritrean Nakfa',
//     symbol_native: 'Nfk',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'ERN',
//     name_plural: 'Eritrean nakfas',
//   },
//   ETB: {
//     symbol: 'Br',
//     name: 'Ethiopian Birr',
//     symbol_native: 'Br',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'ETB',
//     name_plural: 'Ethiopian birrs',
//   },
//   GBP: {
//     symbol: '£',
//     name: 'British Pound Sterling',
//     symbol_native: '£',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'GBP',
//     name_plural: 'British pounds sterling',
//   },
//   GEL: {
//     symbol: 'GEL',
//     name: 'Georgian Lari',
//     symbol_native: 'GEL',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'GEL',
//     name_plural: 'Georgian laris',
//   },
//   GHS: {
//     symbol: 'GH₵',
//     name: 'Ghanaian Cedi',
//     symbol_native: 'GH₵',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'GHS',
//     name_plural: 'Ghanaian cedis',
//   },
//   GNF: {
//     symbol: 'FG',
//     name: 'Guinean Franc',
//     symbol_native: 'FG',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'GNF',
//     name_plural: 'Guinean francs',
//   },
//   GTQ: {
//     symbol: 'GTQ',
//     name: 'Guatemalan Quetzal',
//     symbol_native: 'Q',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'GTQ',
//     name_plural: 'Guatemalan quetzals',
//   },
//   HKD: {
//     symbol: 'HK$',
//     name: 'Hong Kong Dollar',
//     symbol_native: '$',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'HKD',
//     name_plural: 'Hong Kong dollars',
//   },
//   HNL: {
//     symbol: 'HNL',
//     name: 'Honduran Lempira',
//     symbol_native: 'L',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'HNL',
//     name_plural: 'Honduran lempiras',
//   },
//   HRK: {
//     symbol: 'kn',
//     name: 'Croatian Kuna',
//     symbol_native: 'kn',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'HRK',
//     name_plural: 'Croatian kunas',
//   },
//   HUF: {
//     symbol: 'Ft',
//     name: 'Hungarian Forint',
//     symbol_native: 'Ft',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'HUF',
//     name_plural: 'Hungarian forints',
//   },
//   IDR: {
//     symbol: 'Rp',
//     name: 'Indonesian Rupiah',
//     symbol_native: 'Rp',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'IDR',
//     name_plural: 'Indonesian rupiahs',
//   },
//   ILS: {
//     symbol: '₪',
//     name: 'Israeli New Sheqel',
//     symbol_native: '₪',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'ILS',
//     name_plural: 'Israeli new sheqels',
//   },
//   INR: {
//     symbol: 'Rs',
//     name: 'Indian Rupee',
//     symbol_native: 'টকা',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'INR',
//     name_plural: 'Indian rupees',
//   },
//   IQD: {
//     symbol: 'IQD',
//     name: 'Iraqi Dinar',
//     symbol_native: 'د.ع.‏',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'IQD',
//     name_plural: 'Iraqi dinars',
//   },
//   IRR: {
//     symbol: 'IRR',
//     name: 'Iranian Rial',
//     symbol_native: '﷼',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'IRR',
//     name_plural: 'Iranian rials',
//   },
//   ISK: {
//     symbol: 'Ikr',
//     name: 'Icelandic Króna',
//     symbol_native: 'kr',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'ISK',
//     name_plural: 'Icelandic krónur',
//   },
//   JMD: {
//     symbol: 'J$',
//     name: 'Jamaican Dollar',
//     symbol_native: '$',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'JMD',
//     name_plural: 'Jamaican dollars',
//   },
//   JOD: {
//     symbol: 'JD',
//     name: 'Jordanian Dinar',
//     symbol_native: 'د.أ.‏',
//     decimal_digits: 3,
//     rounding: 0,
//     code: 'JOD',
//     name_plural: 'Jordanian dinars',
//   },
//   JPY: {
//     symbol: '¥',
//     name: 'Japanese Yen',
//     symbol_native: '￥',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'JPY',
//     name_plural: 'Japanese yen',
//   },
//   KES: {
//     symbol: 'Ksh',
//     name: 'Kenyan Shilling',
//     symbol_native: 'Ksh',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'KES',
//     name_plural: 'Kenyan shillings',
//   },
//   KHR: {
//     symbol: 'KHR',
//     name: 'Cambodian Riel',
//     symbol_native: '៛',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'KHR',
//     name_plural: 'Cambodian riels',
//   },
//   KMF: {
//     symbol: 'CF',
//     name: 'Comorian Franc',
//     symbol_native: 'FC',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'KMF',
//     name_plural: 'Comorian francs',
//   },
//   KRW: {
//     symbol: '₩',
//     name: 'South Korean Won',
//     symbol_native: '₩',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'KRW',
//     name_plural: 'South Korean won',
//   },
//   KWD: {
//     symbol: 'KD',
//     name: 'Kuwaiti Dinar',
//     symbol_native: 'د.ك.‏',
//     decimal_digits: 3,
//     rounding: 0,
//     code: 'KWD',
//     name_plural: 'Kuwaiti dinars',
//   },
//   KZT: {
//     symbol: 'KZT',
//     name: 'Kazakhstani Tenge',
//     symbol_native: 'тңг.',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'KZT',
//     name_plural: 'Kazakhstani tenges',
//   },
//   LBP: {
//     symbol: 'L.L.',
//     name: 'Lebanese Pound',
//     symbol_native: 'ل.ل.‏',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'LBP',
//     name_plural: 'Lebanese pounds',
//   },
//   LKR: {
//     symbol: 'SLRs',
//     name: 'Sri Lankan Rupee',
//     symbol_native: 'SL Re',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'LKR',
//     name_plural: 'Sri Lankan rupees',
//   },
//   LTL: {
//     symbol: 'Lt',
//     name: 'Lithuanian Litas',
//     symbol_native: 'Lt',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'LTL',
//     name_plural: 'Lithuanian litai',
//   },
//   LVL: {
//     symbol: 'Ls',
//     name: 'Latvian Lats',
//     symbol_native: 'Ls',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'LVL',
//     name_plural: 'Latvian lati',
//   },
//   LYD: {
//     symbol: 'LD',
//     name: 'Libyan Dinar',
//     symbol_native: 'د.ل.‏',
//     decimal_digits: 3,
//     rounding: 0,
//     code: 'LYD',
//     name_plural: 'Libyan dinars',
//   },
//   MAD: {
//     symbol: 'MAD',
//     name: 'Moroccan Dirham',
//     symbol_native: 'د.م.‏',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'MAD',
//     name_plural: 'Moroccan dirhams',
//   },
//   MDL: {
//     symbol: 'MDL',
//     name: 'Moldovan Leu',
//     symbol_native: 'MDL',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'MDL',
//     name_plural: 'Moldovan lei',
//   },
//   MGA: {
//     symbol: 'MGA',
//     name: 'Malagasy Ariary',
//     symbol_native: 'MGA',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'MGA',
//     name_plural: 'Malagasy Ariaries',
//   },
//   MKD: {
//     symbol: 'MKD',
//     name: 'Macedonian Denar',
//     symbol_native: 'MKD',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'MKD',
//     name_plural: 'Macedonian denari',
//   },
//   MMK: {
//     symbol: 'MMK',
//     name: 'Myanma Kyat',
//     symbol_native: 'K',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'MMK',
//     name_plural: 'Myanma kyats',
//   },
//   MOP: {
//     symbol: 'MOP$',
//     name: 'Macanese Pataca',
//     symbol_native: 'MOP$',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'MOP',
//     name_plural: 'Macanese patacas',
//   },
//   MUR: {
//     symbol: 'MURs',
//     name: 'Mauritian Rupee',
//     symbol_native: 'MURs',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'MUR',
//     name_plural: 'Mauritian rupees',
//   },
//   MXN: {
//     symbol: 'MX$',
//     name: 'Mexican Peso',
//     symbol_native: '$',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'MXN',
//     name_plural: 'Mexican pesos',
//   },
//   MYR: {
//     symbol: 'RM',
//     name: 'Malaysian Ringgit',
//     symbol_native: 'RM',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'MYR',
//     name_plural: 'Malaysian ringgits',
//   },
//   MZN: {
//     symbol: 'MTn',
//     name: 'Mozambican Metical',
//     symbol_native: 'MTn',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'MZN',
//     name_plural: 'Mozambican meticals',
//   },
//   NAD: {
//     symbol: 'N$',
//     name: 'Namibian Dollar',
//     symbol_native: 'N$',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'NAD',
//     name_plural: 'Namibian dollars',
//   },
//   NGN: {
//     symbol: '₦',
//     name: 'Nigerian Naira',
//     symbol_native: '₦',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'NGN',
//     name_plural: 'Nigerian nairas',
//   },
//   NIO: {
//     symbol: 'C$',
//     name: 'Nicaraguan Córdoba',
//     symbol_native: 'C$',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'NIO',
//     name_plural: 'Nicaraguan córdobas',
//   },
//   NOK: {
//     symbol: 'Nkr',
//     name: 'Norwegian Krone',
//     symbol_native: 'kr',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'NOK',
//     name_plural: 'Norwegian kroner',
//   },
//   NPR: {
//     symbol: 'NPRs',
//     name: 'Nepalese Rupee',
//     symbol_native: 'नेरू',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'NPR',
//     name_plural: 'Nepalese rupees',
//   },
//   NZD: {
//     symbol: 'NZ$',
//     name: 'New Zealand Dollar',
//     symbol_native: '$',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'NZD',
//     name_plural: 'New Zealand dollars',
//   },
//   OMR: {
//     symbol: 'OMR',
//     name: 'Omani Rial',
//     symbol_native: 'ر.ع.‏',
//     decimal_digits: 3,
//     rounding: 0,
//     code: 'OMR',
//     name_plural: 'Omani rials',
//   },
//   PAB: {
//     symbol: 'B/.',
//     name: 'Panamanian Balboa',
//     symbol_native: 'B/.',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'PAB',
//     name_plural: 'Panamanian balboas',
//   },
//   PEN: {
//     symbol: 'S/.',
//     name: 'Peruvian Nuevo Sol',
//     symbol_native: 'S/.',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'PEN',
//     name_plural: 'Peruvian nuevos soles',
//   },
//   PHP: {
//     symbol: '₱',
//     name: 'Philippine Peso',
//     symbol_native: '₱',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'PHP',
//     name_plural: 'Philippine pesos',
//   },
//   PKR: {
//     symbol: 'PKRs',
//     name: 'Pakistani Rupee',
//     symbol_native: '₨',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'PKR',
//     name_plural: 'Pakistani rupees',
//   },
//   PLN: {
//     symbol: 'zł',
//     name: 'Polish Zloty',
//     symbol_native: 'zł',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'PLN',
//     name_plural: 'Polish zlotys',
//   },
//   PYG: {
//     symbol: '₲',
//     name: 'Paraguayan Guarani',
//     symbol_native: '₲',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'PYG',
//     name_plural: 'Paraguayan guaranis',
//   },
//   QAR: {
//     symbol: 'QR',
//     name: 'Qatari Rial',
//     symbol_native: 'ر.ق.‏',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'QAR',
//     name_plural: 'Qatari rials',
//   },
//   RON: {
//     symbol: 'RON',
//     name: 'Romanian Leu',
//     symbol_native: 'RON',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'RON',
//     name_plural: 'Romanian lei',
//   },
//   RSD: {
//     symbol: 'din.',
//     name: 'Serbian Dinar',
//     symbol_native: 'дин.',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'RSD',
//     name_plural: 'Serbian dinars',
//   },
//   RUB: {
//     symbol: 'RUB',
//     name: 'Russian Ruble',
//     symbol_native: '₽.',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'RUB',
//     name_plural: 'Russian rubles',
//   },
//   RWF: {
//     symbol: 'RWF',
//     name: 'Rwandan Franc',
//     symbol_native: 'FR',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'RWF',
//     name_plural: 'Rwandan francs',
//   },
//   SAR: {
//     symbol: 'SR',
//     name: 'Saudi Riyal',
//     symbol_native: 'ر.س.‏',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'SAR',
//     name_plural: 'Saudi riyals',
//   },
//   SDG: {
//     symbol: 'SDG',
//     name: 'Sudanese Pound',
//     symbol_native: 'SDG',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'SDG',
//     name_plural: 'Sudanese pounds',
//   },
//   SEK: {
//     symbol: 'Skr',
//     name: 'Swedish Krona',
//     symbol_native: 'kr',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'SEK',
//     name_plural: 'Swedish kronor',
//   },
//   SGD: {
//     symbol: 'S$',
//     name: 'Singapore Dollar',
//     symbol_native: '$',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'SGD',
//     name_plural: 'Singapore dollars',
//   },
//   SOS: {
//     symbol: 'Ssh',
//     name: 'Somali Shilling',
//     symbol_native: 'Ssh',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'SOS',
//     name_plural: 'Somali shillings',
//   },
//   SYP: {
//     symbol: 'SY£',
//     name: 'Syrian Pound',
//     symbol_native: 'ل.س.‏',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'SYP',
//     name_plural: 'Syrian pounds',
//   },
//   THB: {
//     symbol: '฿',
//     name: 'Thai Baht',
//     symbol_native: '฿',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'THB',
//     name_plural: 'Thai baht',
//   },
//   TND: {
//     symbol: 'DT',
//     name: 'Tunisian Dinar',
//     symbol_native: 'د.ت.‏',
//     decimal_digits: 3,
//     rounding: 0,
//     code: 'TND',
//     name_plural: 'Tunisian dinars',
//   },
//   TOP: {
//     symbol: 'T$',
//     name: 'Tongan Paʻanga',
//     symbol_native: 'T$',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'TOP',
//     name_plural: 'Tongan paʻanga',
//   },
//   TRY: {
//     symbol: 'TL',
//     name: 'Turkish Lira',
//     symbol_native: 'TL',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'TRY',
//     name_plural: 'Turkish Lira',
//   },
//   TTD: {
//     symbol: 'TT$',
//     name: 'Trinidad and Tobago Dollar',
//     symbol_native: '$',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'TTD',
//     name_plural: 'Trinidad and Tobago dollars',
//   },
//   TWD: {
//     symbol: 'NT$',
//     name: 'New Taiwan Dollar',
//     symbol_native: 'NT$',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'TWD',
//     name_plural: 'New Taiwan dollars',
//   },
//   TZS: {
//     symbol: 'TSh',
//     name: 'Tanzanian Shilling',
//     symbol_native: 'TSh',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'TZS',
//     name_plural: 'Tanzanian shillings',
//   },
//   UAH: {
//     symbol: '₴',
//     name: 'Ukrainian Hryvnia',
//     symbol_native: '₴',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'UAH',
//     name_plural: 'Ukrainian hryvnias',
//   },
//   UGX: {
//     symbol: 'USh',
//     name: 'Ugandan Shilling',
//     symbol_native: 'USh',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'UGX',
//     name_plural: 'Ugandan shillings',
//   },
//   UYU: {
//     symbol: '$U',
//     name: 'Uruguayan Peso',
//     symbol_native: '$',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'UYU',
//     name_plural: 'Uruguayan pesos',
//   },
//   UZS: {
//     symbol: 'UZS',
//     name: 'Uzbekistan Som',
//     symbol_native: 'UZS',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'UZS',
//     name_plural: 'Uzbekistan som',
//   },
//   VEF: {
//     symbol: 'Bs.F.',
//     name: 'Venezuelan Bolívar',
//     symbol_native: 'Bs.F.',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'VEF',
//     name_plural: 'Venezuelan bolívars',
//   },
//   VND: {
//     symbol: '₫',
//     name: 'Vietnamese Dong',
//     symbol_native: '₫',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'VND',
//     name_plural: 'Vietnamese dong',
//   },
//   XAF: {
//     symbol: 'FCFA',
//     name: 'CFA Franc BEAC',
//     symbol_native: 'FCFA',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'XAF',
//     name_plural: 'CFA francs BEAC',
//   },
//   XOF: {
//     symbol: 'CFA',
//     name: 'CFA Franc BCEAO',
//     symbol_native: 'CFA',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'XOF',
//     name_plural: 'CFA francs BCEAO',
//   },
//   YER: {
//     symbol: 'YR',
//     name: 'Yemeni Rial',
//     symbol_native: 'ر.ي.‏',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'YER',
//     name_plural: 'Yemeni rials',
//   },
//   ZAR: {
//     symbol: 'R',
//     name: 'South African Rand',
//     symbol_native: 'R',
//     decimal_digits: 2,
//     rounding: 0,
//     code: 'ZAR',
//     name_plural: 'South African rand',
//   },
//   ZMK: {
//     symbol: 'ZK',
//     name: 'Zambian Kwacha',
//     symbol_native: 'ZK',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'ZMK',
//     name_plural: 'Zambian kwachas',
//   },
//   ZWL: {
//     symbol: 'ZWL$',
//     name: 'Zimbabwean Dollar',
//     symbol_native: 'ZWL$',
//     decimal_digits: 0,
//     rounding: 0,
//     code: 'ZWL',
//     name_plural: 'Zimbabwean Dollar',
//   },
// };
